name: CI - Build Backend

# --------------------------------------------------
# Workflow trigger
# --------------------------------------------------
on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**

jobs:
  name: CI - Build Backend
  build:
    runs-on: ubuntu-latest

    # --------------------------------------------------
    # PostgreSQL service container
    # --------------------------------------------------
    services:
      postgres:
        image: postgres:18.3
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: customer
        ports:
          - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          

    # --------------------------------------------------
    # Set backend as the working directory
    # --------------------------------------------------
    defaults:
      run:
        working-directory: ./backend


    steps:
      # --------------------------------------------------
      # Checkout repository
      # --------------------------------------------------
      - uses: actions/checkout@v7

      # --------------------------------------------------
      # Setup Java 17 and Maven dependency caching
      # --------------------------------------------------
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # --------------------------------------------------
      # Build backend and run unit/integration tests
      # --------------------------------------------------
      - name: Build and run Unit/Integration Tests with Maven
        env:
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: mvn -ntp -B verify
